addScript
kadalu/kadalu pull request #152
Opened 2020-01-28 07:36 UTC by vatsa287

2020-02-06 16:17 UTC, amarts commented
@vatsa287 I am not sure such scripts are of a choice to many people because they may have some experience already by the time they start with deploying the project. May be it is a good thing to add in a blog, and say you did use it.

But thinking more about it, you can extend such behavior with `kubectl kadalu` CLI itself. If there are no arguments given, it can ask for next steps interactively. And as it already has options to manage yaml files, that may be a better place to start this.

2020-02-06 16:17 UTC, amarts requested changes
marking request changes as I prefer it to be done through CLI at least.

2020-02-07 04:56 UTC, vatsa287 commented
> marking request changes as I prefer it to be done through CLI at least.

sure thing.

2020-05-11 15:00 UTC, amarts commented
IMO, this flow is not required for any k8s user, as most of them would be aware of how to setup the config files! Instead the best PR to work on would be the #45 as a first-timer!

2020-05-11 15:28 UTC, vatsa287 commented
Yes , I will look into it and try to learn

2020-10-27 13:04 UTC, amarts commented
Can you make the script without `kubectl-kadalu` package? but with a template storage yaml file, which gets replaced with proper variables based on the arguments?

2020-10-27 13:12 UTC, amarts requested changes

2020-10-27 13:12 UTC, amarts commented on extras/scripts/kadalu-quick-start-generic.sh
> +       sudo kubectl create -f https://kadalu.io/operator-latest.yaml
sudo kubectl apply -f https://raw.githubusercontent.com/kadalu/kadalu/devel/manifests/kadalu-operator.yaml

2020-10-27 13:12 UTC, amarts commented on extras/scripts/kadalu-quick-start-generic.sh
> +                sudo kubectl kadalu storage-add $storagePool --device $device:$devPath
no need for kubectl kadalu... the script should run without python dependency!

2020-10-27 13:12 UTC, amarts commented on extras/scripts/kadalu-quick-start-generic.sh
> +        sudo kubectl get pods
can you use `getopt` and take these variables as arguments instead. Also provide '--help'.

2020-10-27 13:12 UTC, amarts commented on extras/scripts/kadalu-quick-start-generic.sh
> +        sleep 100
no need to sleep 100, but do it like https://github.com/kadalu/kadalu/blob/devel/tests/minikube.sh#L11

2020-11-20 07:11 UTC, vatsa287 commented
Changes done through patch #327 .

2020-11-20 07:11 UTC, closed without merging